### ISSUE TITLE
Build Header & Footer

### ISSUE THREAD

**Issue by muathkhatib** [GSG-G10/news-website-team-5#1]
# Header and Footer updates:

This issue #1 is for Branch Header&Footer.

**Comment by umarsalah** [comment]
# Updates:

1-Create HTML&CSS files .

2-Create navBar. 

3-Create siteFace Bar.

**Comment by umarsalah** [comment]
# Header Finished 

Added the last navigation bar and finish the Header, it's fully Responsive.

**Comment by umarsalah** [comment]
# Footer Finished

Footer submitted.

**Comment by umarsalah** [comment]
This Issue about to be closed, Waiting for a Review from others.
